[workspace]
resolver = "2"
members = ["cuda", "graph", "rocky", "runtime", "schema"]

[workspace.dependencies]
# Memory arenas.
bumpalo = "3.16"

# Useful numerical type extensions.
num-traits = "0.2"

# Benchmarking.
criterion = { version = "0.5", default-features = false }

cudarc = {  git = "https://github.com/kckeiks/cudarc", branch = "softmax-support", default-features = false, features = ["cublas", "cudnn", "cuda-version-from-build-system", "driver", "f16", "dynamic-loading"]}

