[package]
name = "rocky"
version = "0.0.0"
edition = "2021"
authors = ["M. Meier <m.wiresurfer@gmail.com>"]

[dependencies]
anyhow = "1.0"
bincode = "1.3"
clap = { version = "4.5", features = ["derive", "string"] }
rmlk-schema = { path = "../schema" }
rmlk-graph = { path = "../graph" }
quick-protobuf = "0.8"
log = "0.4.21"
