[package]
name = "rmlk-runtime"
version = "0.0.0"
edition = "2021"
authors = ["M. Meier <mi9uel9@gmail.com>"]

[dependencies]
# Memory arenas.
bumpalo.workspace = true

bincode = "1.3.3"
cudarc.workspace = true
half = "2.4"
log = "0.4"
ndarray = "0.15"
num-traits.workspace = true
rmlk-schema = { path = "../schema" }
rmlk-graph = { path = "../graph" }
rmlk-cuda = { path = "../cuda" }

[dev-dependencies]
image = "0.24"

