[package]
name = "rmlk-runtime"
version = "0.0.0"
edition = "2021"
authors = ["M. Meier <mi9uel9@gmail.com>"]

[dependencies]
anyhow.workspace = true
bincode.workspace = true
bumpalo.workspace = true
cudarc.workspace = true
half.workspace = true
log.workspace = true
num-traits.workspace = true
base64 = { workspace = true, optional = true }

rmlk-schema = { path = "../schema" }
rmlk-graph = { path = "../graph" }
rmlk-cuda = { path = "../cuda" }

[dev-dependencies]
approx = "0.5"
env_logger = "0.11"
image = "0.24"
ndarray = "0.15"
serde.workspace = true
serde_json.workspace = true
tokenizers = "0.21"

[features]
debugger = ["base64"]

