[package]
name = "rmlk-tensor"
version = "0.0.0"
edition = "2021"
authors = ["M. Meier <mi9uel9@gmail.com>"]

[dependencies]
rmlk-cuda = { path = "../cuda" }
cudarc = {  version = "0.11", default-features = false, features = ["cublas", "cuda-version-from-build-system", "driver", "f16"]}
half = "2.4"

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "bench_main"
harness = false
