[package]
name = "rmlk-tensor"
version = "0.0.0"
edition = "2021"
authors = ["M. Meier <mi9uel9@gmail.com>"]

[dependencies]
cudarc = {  git = "https://github.com/kckeiks/cudarc.git", branch = "add-pooling", default-features = false, features = ["cublas", "cudnn", "cuda-version-from-build-system", "driver", "f16"]}
rmlk-cuda = { path = "../cuda" }
rmlk-ir = { path = "../ir" }
rmlk-graph = { path = "../graph" }
half = "2.4"
log = "0.4.21"

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "bench_main"
harness = false
