#include "binary_op_macros.cuh"
#include "cuda_fp16.h"

#include <stdint.h>

BINARY_OP_WITH_INPUT_TYPES(__half, uint8_t,  pow_fwd_f16_u8,  powf(__half2float(x), static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(__half, uint16_t, pow_fwd_f16_u16, powf(__half2float(x), static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(__half, uint32_t, pow_fwd_f16_u32, powf(__half2float(x), static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(__half, uint64_t, pow_fwd_f16_u64, powf(__half2float(x), static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(__half, int8_t,   pow_fwd_f16_i8,  powf(__half2float(x), static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(__half, int16_t,  pow_fwd_f16_i16, powf(__half2float(x), static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(__half, int32_t,  pow_fwd_f16_i32, powf(__half2float(x), static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(__half, int64_t,  pow_fwd_f16_i64, powf(__half2float(x), static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(__half, __half,   pow_fwd_f16_f16, powf(__half2float(x), __half2float(y)))
BINARY_OP_WITH_INPUT_TYPES(__half, float,    pow_fwd_f16_f32, powf(__half2float(x), y))
BINARY_OP_WITH_INPUT_TYPES(__half, double,   pow_fwd_f16_f64, powf(__half2float(x), static_cast<float>(y)))

BINARY_OP_WITH_INPUT_TYPES(float, uint8_t,  pow_fwd_f32_u8,  powf(x, static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(float, uint16_t, pow_fwd_f32_u16, powf(x, static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(float, uint32_t, pow_fwd_f32_u32, powf(x, static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(float, uint64_t, pow_fwd_f32_u64, powf(x, static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(float, int8_t,   pow_fwd_f32_i8,  powf(x, static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(float, int16_t,  pow_fwd_f32_i16, powf(x, static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(float, int32_t,  pow_fwd_f32_i32, powf(x, static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(float, int64_t,  pow_fwd_f32_i64, powf(x, static_cast<float>(y)))
BINARY_OP_WITH_INPUT_TYPES(float, __half,   pow_fwd_f32_f16, powf(x, __half2float(y)))
BINARY_OP_WITH_INPUT_TYPES(float, float,    pow_fwd_f32_f32, powf(x, y))
BINARY_OP_WITH_INPUT_TYPES(float, double,   pow_fwd_f32_f64, powf(x, static_cast<float>(y)))


BINARY_OP_WITH_INPUT_TYPES(double, uint8_t,  pow_fwd_f64_u8,  pow(x, static_cast<double>(y)))
BINARY_OP_WITH_INPUT_TYPES(double, uint16_t, pow_fwd_f64_u16, pow(x, static_cast<double>(y)))
BINARY_OP_WITH_INPUT_TYPES(double, uint32_t, pow_fwd_f64_u32, pow(x, static_cast<double>(y)))
BINARY_OP_WITH_INPUT_TYPES(double, uint64_t, pow_fwd_f64_u64, pow(x, static_cast<double>(y)))
BINARY_OP_WITH_INPUT_TYPES(double, int8_t,   pow_fwd_f64_i8,  pow(x, static_cast<double>(y)))
BINARY_OP_WITH_INPUT_TYPES(double, int16_t,  pow_fwd_f64_i16, pow(x, static_cast<double>(y)))
BINARY_OP_WITH_INPUT_TYPES(double, int32_t,  pow_fwd_f64_i32, pow(x, static_cast<double>(y)))
BINARY_OP_WITH_INPUT_TYPES(double, int64_t,  pow_fwd_f64_i64, pow(x, static_cast<double>(y)))
BINARY_OP_WITH_INPUT_TYPES(double, __half,   pow_fwd_f64_f16, pow(x, static_cast<double>(__half2float(y))))
BINARY_OP_WITH_INPUT_TYPES(double, float,    pow_fwd_f64_f32, pow(x, static_cast<double>(y)))
BINARY_OP_WITH_INPUT_TYPES(double, double,   pow_fwd_f64_f64, pow(x, y))

BINARY_OP_WITH_INPUT_TYPES(int32_t, uint8_t,  pow_fwd_i32_u8,  static_cast<int32_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int32_t, uint16_t, pow_fwd_i32_u16, static_cast<int32_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int32_t, uint32_t, pow_fwd_i32_u32, static_cast<int32_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int32_t, uint64_t, pow_fwd_i32_u64, static_cast<int32_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int32_t, int8_t,   pow_fwd_i32_i8,  static_cast<int32_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int32_t, int16_t,  pow_fwd_i32_i16, static_cast<int32_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int32_t, int32_t,  pow_fwd_i32_i32, static_cast<int32_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int32_t, int64_t,  pow_fwd_i32_i64, static_cast<int32_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int32_t, __half,   pow_fwd_i32_f16, static_cast<int32_t>(llround(pow(static_cast<double>(x), static_cast<double>(__half2float(y))))))
BINARY_OP_WITH_INPUT_TYPES(int32_t, float,    pow_fwd_i32_f32, static_cast<int32_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int32_t, double,   pow_fwd_i32_f64, static_cast<int32_t>(llround(pow(static_cast<double>(x), y))))

BINARY_OP_WITH_INPUT_TYPES(int64_t, uint8_t,  pow_fwd_i64_u8,  static_cast<int64_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int64_t, uint16_t, pow_fwd_i64_u16, static_cast<int64_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int64_t, uint32_t, pow_fwd_i64_u32, static_cast<int64_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int64_t, uint64_t, pow_fwd_i64_u64, static_cast<int64_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int64_t, int8_t,   pow_fwd_i64_i8,  static_cast<int64_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int64_t, int16_t,  pow_fwd_i64_i16, static_cast<int64_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int64_t, int32_t,  pow_fwd_i64_i32, static_cast<int64_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int64_t, int64_t,  pow_fwd_i64_i64, static_cast<int64_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int64_t, __half,   pow_fwd_i64_f16, static_cast<int64_t>(llround(pow(static_cast<double>(x), static_cast<double>(__half2float(y))))))
BINARY_OP_WITH_INPUT_TYPES(int64_t, float,    pow_fwd_i64_f32, static_cast<int64_t>(llround(pow(static_cast<double>(x), static_cast<double>(y)))))
BINARY_OP_WITH_INPUT_TYPES(int64_t, double,   pow_fwd_i64_f64, static_cast<int64_t>(llround(pow(static_cast<double>(x), y))))
